version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
     
  pre_build:
    commands:
      
  build:
    commands:
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist